export const currentEditors = [
  {
    id: 0,
    name: "Akeredola Favour",
    position: "Editor-In-Chief",
    img: "",
  },
  {
    id: 1,
    name: "Chisom David Emmanuel",
    position: "Editor",
    img: "",
  },
  {
    id: 2,
    name: "Gideon Lucky Chukwuka",
    position: "Website Editor",
    img: "",
  },
  {
    id: 3,
    name: "Agunbiade Marvellous",
    position: "News Editor",
    img: "",
  },
  {
    id: 4,
    name: "Ani Blessing Chioma",
    position: "Business & Economy Editor",
    img: "",
  },
  {
    id: 5,
    name: "Jaiyeola Joana",
    position: "Politics Editor",
    img: "",
  },
  {
    id: 6,
    name: "Ayejuyo Bamikole Courage",
    position: "Sport Editor",
    img: "",
  },
  {
    id: 7,
    name: "Oyetunji Ifeoluwa",
    position: "Assistant Production Manager",
    img: "",
  },
  {
    id: 8,
    name: "Ayela Blessing Anjola",
    position: "Lifestyle Editor",
    img: "",
  },
  {
    id: 9,
    name: "Tubonemi Esther Belema",
    position: "Advert Manager",
    img: "",
  },
  {
    id: 10,
    name: "Ayegba David Oche",
    position: "Foreign Page Editor",
    img: "",
  },
  {
    id: 11,
    name: "Aina Tola Emmanuel",
    position: "Entertainment Editor",
    img: "",
  },
  {
    id: 12,
    name: "Ajayi Love",
    position: "Education Editor",
    img: "",
  },
  {
    id: 13,
    name: "Ogunnaike Faith Toluwalase",
    position: "Assistant Arts and Culture Editor",
    img: "",
  },
  {
    id: 14,
    name: "Igboanusi Chiamaka",
    position: "Production Editor",
    img: "",
  },
  {
    id: 15,
    name: "Moronu Chidera",
    position: "Assistant Advert Manager",
    img: "",
  },
];

export const editorialAdvicers = [
  {
    id: 0,
    title: "Prof",
    name: "Olusola Oyero",
    position: "Dean, Faculty of Social and Management Sciences",
    img: "",
  },
  {
    id: 1,
    title: "Dr",
    name: "Emmanuel Ifeduba",
    position: "Head of Department, Mass Communication",
    img: "",
  },
  {
    id: 2,
    title: "Mr",
    name: "Charles Okonji",
    position: "News Writing and Reporting Lecturer",
    img: "",
  },
  {
    id: 3,
    title: "Mr",
    name: "Ayo",
    position: "Technologist",
    img: "",
  },
  {
    id: 4,
    title: "Mrs",
    name: "Tope",
    position: "Technologist",
    img: "",
  },
];

export const foundingEditors = [
  {
    id: 0,
    name: "Akeredola Favour",
    position: "Editor-In-Chief",
    img: "",
  },
  {
    id: 1,
    name: "Chisom David Emmanuel",
    position: "Editor",
    img: "",
  },
  {
    id: 2,
    name: "Gideon Lucky Chukwuka",
    position: "Website Editor",
    img: "",
  },
  {
    id: 3,
    name: "Agunbiade Marvellous",
    position: "News Editor",
    img: "",
  },
  {
    id: 4,
    name: "Ani Blessing Chioma",
    position: "Business & Economy Editor",
    img: "",
  },
  {
    id: 5,
    name: "Jaiyeola Joana",
    position: "Politics Editor",
    img: "",
  },
  {
    id: 6,
    name: "Ayejuyo Bamikole Courage",
    position: "Sport Editor",
    img: "",
  },
  {
    id: 7,
    name: "Oyetunji Ifeoluwa",
    position: "Assistant Production Manager",
    img: "",
  },
  {
    id: 8,
    name: "Ayela Blessing Anjola",
    position: "Lifestyle Editor",
    img: "",
  },
  {
    id: 9,
    name: "Tubonemi Esther Belema",
    position: "Advert Manager",
    img: "",
  },
  {
    id: 10,
    name: "Ayegba David Oche",
    position: "Foreign Page Editor",
    img: "",
  },
  {
    id: 11,
    name: "Aina Tola Emmanuel",
    position: "Entertainment Editor",
    img: "",
  },
  {
    id: 12,
    name: "Ajayi Love",
    position: "Education Editor",
    img: "",
  },
  {
    id: 13,
    name: "Ogunnaike Faith Toluwalase",
    position: "Assistant Arts and Culture Editor",
    img: "",
  },
  {
    id: 14,
    name: "Igboanusi Chiamaka",
    position: "Production Editor",
    img: "",
  },
  {
    id: 15,
    name: "Moronu Chidera",
    position: "Assistant Advert Manager",
    img: "",
  },
];
